# Generated by Django 2.0.6 on 2018-06-22 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180614_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
