# Generated by Django 2.0.6 on 2018-06-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180622_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cat_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
