# Generated by Django 2.0.6 on 2018-06-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180623_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='cat_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='id2',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id1',
        ),
    ]
