# Generated by Django 2.0.6 on 2018-06-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180623_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cat_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
